# Generated by Django 2.1.5 on 2024-03-03 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='UserName',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='app.UserAccount'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.UserAccount'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app.UserAccount'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='app.UserAccount'),
        ),
        migrations.AlterField(
            model_name='reported_recipe',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='app.UserAccount'),
        ),
    ]
