# Generated by Django 2.1.5 on 2024-03-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240303_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Origin',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='Type',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
