# Generated by Django 2.1.5 on 2024-03-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240310_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('SupportID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=30)),
                ('SupportDescription', models.CharField(max_length=200)),
                ('SupportDate', models.DateTimeField()),
            ],
        ),
    ]
