# Generated by Django 2.1.5 on 2024-03-13 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='collection',
            name='User',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='Collection',
        ),
        migrations.AddField(
            model_name='recipe',
            name='Image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.AddField(
            model_name='favourites',
            name='Recipes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='app.Recipe'),
        ),
        migrations.AddField(
            model_name='favourites',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='app.UserAccount'),
        ),
    ]
