# Generated by Django 2.1.5 on 2024-03-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20240313_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='Favourites',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='Favourites',
            field=models.ManyToManyField(blank=True, null=True, to='app.Recipe'),
        ),
    ]
