# Generated by Django 2.1.5 on 2024-03-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20240314_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='Favourites',
            field=models.ManyToManyField(blank=True, to='app.Recipe'),
        ),
    ]
